### ISSUE TITLE
Uninitialized constant ActiveSupport::Dependencies::Mutex

### ISSUE THREAD

**Issue by andyw8** [databasically/lowdown#1]
When I run rake:schema:load I get "Uninitialized constant ActiveSupport::Dependencies::Mutex"

According to [this SO post](http://stackoverflow.com/questions/5176782/uninitialized-constant-activesupportdependenciesmutex-nameerror) it's caused by an incompatability between Rails 2.3.5 and newer versions of Bundler.

**Comment by andyw8** [comment]
Pull request #3 should fix this

**Comment by wesgarrison** [comment]
We should probably just delete the migrations, they're not supported.  Instead, load the schema.rb file.  I'll check #3 too.

**Comment by andyw8** [comment]
+1 for deleting the migrations
